name: Tests

on: [push, release]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
      - name: Build
        run: pnpm turbo build --filter='@libs/*'
      - name: Install Playwright Browsers
        working-directory: ./@apps/e2e
        run: pnpm exec playwright install --with-deps
      - name: Lint
        run: pnpm turbo lint
      - name: Run tests
        run: pnpm turbo test --filter='!@apps/e2e' --concurrency=1